version: '3.9'

name: email-service-app
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .docker.env
    container_name: app
    networks:
      - email-service
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - email-service
    restart: unless-stopped
    depends_on:
      - app

  # PostgreSQL (latest stable)
  postgres:
    image: postgres:17
    container_name: app-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: email_service
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - email-service

  # Redis (latest stable)
  redis:
    image: redis:7
    container_name: app-cache-server
    volumes:
      - redis_data:/data
    networks:
      - email-service

networks:
  email-service:

volumes:
  pg_data:
  redis_data:
